config/routes.rb
Rails.application.routes.draw do

  root to: 'users#show'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  
  resources :courses do
    resources :enrollments do
      put :approving
      put :rejecting
    end
    resources :reviews, only: [:create, :destroy]
  end

  resources :rooms do
    resources :bookings do
      put :approving
      put :rejecting 
    end
  end
  
end

app/models/booking.rb
class Booking < ApplicationRecord
  include AASM

  aasm do
    state :reserved, initial: true
    state :rejected, :approved

    event :approving do
      transitions from: :reserved, to: :approved
    end

    event :rejecting do
      after do
        self.destroy
      end
      transitions from: :reserved, to: :rejected
    end

  end
  
  belongs_to :course
  belongs_to :room
  
  validates :start_time, :end_time, presence: true  
  validate :end_time_after_start_time
  validate :available

  private

  def end_time_after_start_time    
    return if end_time.blank? || start_time.blank?
      if end_time < start_time      
        errors.add(:end_time, "Your end time must be after the start time.")    
      end 
  end

  def available
    conflicts = Booking.where(room_id: room_id)
      .where("start_time < ? AND end_time > ?", start_time, start_time)
      .or(Booking.where("start_time < ? AND end_time > ?", end_time, end_time))
      .or(Booking.where("start_time > ? AND end_time < ?", start_time, end_time))

    # puts "HERE IS A LIST OF OUR CONFLICTS"
    # p conflicts
    # puts "number of conflicts: " + conflicts.length.to_s
    # puts conflicts.exists?
    # puts !conflicts.exists?
    if conflicts.exists?
      errors.add(:start_time, "The time you have selected is unavailable. Please select another time slot.")
    end
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    before_action :authenticate_user!, only: [:create, :update, :destroy]
    before_action :find_booking, only: [:update, :destroy]
    before_action :authorize!, only: [:update, :destroy]


    def create
        @room = Room.find(params[:room_id])
        @booking = Booking.new booking_params
        @booking.course.user = current_user
        @booking.room = @room
        if @booking.save
            flash[:success] = "Congratulations! You have booked a room."
            redirect_to room_path(@room)
        else
            @bookings = @room.bookings.order(created_at: :desc)
            render 'rooms/show'
        end
    end

    def edit
        @room = Room.find params[:room_id]
        @booking = Booking.find params[:id]
        @bookings = @room.bookings.order(created_at: :desc)
        @courses  = current_user.courses
    end

    def update
        @booking.update booking_params
        redirect_to room_path(@booking.room)
    end

    def destroy
        @booking.destroy
        flash[:notice] = 'The booking has been deleted.'
        redirect_to room_path(@booking.room)
    end

    def approving
        @booking = Booking.find(params[:booking_id])
        @booking.approving!
        redirect_to room_path(@booking.room)
    end

    def rejecting
        @booking = Booking.find(params[:booking_id])
        @booking.rejecting!
        redirect_to room_path(@booking.room)
    end

    private

    def booking_params
        params.require(:booking).permit(:course_id, :room_id, :start_time, :end_time)
    end

    def find_booking
        @booking = Booking.find params[:id]
    end

    def authorize!
        find_booking
        unless can?(:crud, @booking)
            flash[:danger] = "Not Authorized"
            redirect_to room_path(@booking.room)
        end
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="room_book">
    <div class="room_info">
      <h5 class="new user"><%= @room.name %></h5>

      <% if can? :crud, @room %>
      <div class="post-buttons">
        <%= link_to('Edit Room', edit_room_path(@room.id), class: "sign_up_button") %>
        <%= link_to("Delete Room", room_path(@room), method: :delete, data:{confirm:'Are you sure?'}, class: "sign_up_button") %>
      </div>
      <% end %>

      <p>Address: <%= @room.address %></p>
      <p>Location: <%= link_to(
                    @room.location, rooms_path(location: @room.location)
                ) %></p>
      <p><%= @room.capacity %></p>
      <p>$<%= @room.price %></p>
      <p><%= @room.description %></p>

      <% if @room.features.count > 0 %>
      <h6>Features</h6>
      <ul>
        <% @room.features.each do |feature| %>
        <li><%= link_to(
                    feature.name, rooms_path(feature: feature.name)
                ) %></li>
        <% end %>
      </ul>
      <% end %>
    </div>
    <div class="booking_room">
      <%= form_with(model: [@room, @booking], local: true) do |form| %>
      <% if @booking.errors.any? %>
      <div id=“error_explanation”>
        <h2><%= pluralize(@booking.errors.count, “error”) %> prohibited this @booking from being saved:</h2>
        <ul>
          <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class=“field”>
        <%= form.label :start_time %><br />
        <%= form.datetime_select :start_time %>
      </div>
      <div class=“field”>
        <%= form.label :end_time %><br />
        <%= form.datetime_select :end_time %>
      </div>

      <div class=“field”>
        <%= form.label :course_id %><br />
        <%= form.collection_select :course_id, @courses , :id, :title%>
      </div>

      <div class=“actions”>
        <%= link_to 'delete', room_booking_path(@room, @booking), method: :DELETE %>
        <%= form.submit class: "sign_up_button" %>
      </div>
      <% end %>
    </div>
  </div>
  <hr>


  <%= month_calendar events: @bookings do |date, bookings| %>
  <span class="day_number"><%= use_day_only date %></span class="day_number">
    <% bookings.each do |booking| %>
      <div>
        <div>
          <%= booking.start_time.strftime("%I:%M%p") %>
        </div>
          <% if booking.approved? %> 
            <%= booking.course.title %>
            by <%= booking.course.user.first_name %>
          <% else %>
            <small> Pending </small>
            <%= link_to booking.course.title, edit_room_booking_path(@room, booking) %>
          <% end %>
        <div>
          <%= booking.end_time.strftime("%I:%M%p") %>
        </div>
      </div><br>
    <% end %>
  <% end %>

  <% if can?(:crud, @room)%>
  <h2> Reserved Bookings </h2>
    <% @bookings.each do |booking| %>
      <% if booking.reserved? %>
        <%= booking.course.title  %><br>
        <%= button_to "Approve", room_booking_approving_path(@room, booking), method: :put %>
        <%= button_to "Reject", room_booking_rejecting_path(@room, booking), method: :put %>
      <% end %>
    <% end %>
  <% end %>