config/routes.rb
Rails.application.routes.draw do

  root to: 'users#show'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  
  resources :courses do
    resources :enrollments do
      put :approving
      put :rejecting
    end
    resources :reviews, only: [:create, :destroy]
  end

  resources :rooms do
    resources :bookings do
      put :approving
      put :rejecting 
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :is_admin?, default: false
    validates :email, presence: true, uniqueness: true,
    format: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

    has_many :rooms, dependent: :nullify
    has_many :courses, dependent: :nullify 
    has_many :reviews, dependent: :destroy
    has_many :enrolled_courses, through: :enrollment, source: :course   
    has_many :enrollments, dependent: :destroy  

    def full_name
        "#{first_name} #{last_name}"      
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!, except: [:new, :create]
    before_action :authenticate!, only: [:edit, :update, :destroy]
    before_action :find_user, only: [:edit, :update, :destroy, :password_edit, :password_update]


    def new
        @user = User.new 
    end

    def create
        @user = User.new user_params
        if @user.save
            flash[:success] = "User created"
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @user.update user_params
            flash[:success] = "User info updated"
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :edit
        end
    end


    def show
        @user = current_user
    end
  
    def update_password
        if @user&.authenticate params[:current_password]
            user_params[:password] = params[:id][:new_password] 
            if @user.update user_params
                flash[:notice] = "You have updated your password."
                redirect_to root_path
            else
                flash[:alert] = "Password update failed. Please make sure your new password matches its confirmation."
                render :edit_password
            end
        else
            render :edit_password, alert: "Your current password does not match our records."
        end
    end
    
    def edit_password
    end

    private

    def user_params
        params.require(:user).permit(
            :first_name, :last_name, :email, :password, :password_confirmation
        )
    end

    def find_user
        @user = User.find params[:id]
    end

    def authenticate!
        find_user
        unless session[:user_id] === @user.id
            flash[:danger] = "Not Authorized"
            redirect_to root_path
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="sign_up_form">
    <%= form_with model: @user, local: true, class: "ui form" do |f|%>
        <% if @user.errors.any? %>
        <p>
            <%= @user.errors.full_messages.join(',')%>
        </p>
        <% end %>

        <div class="user_name">
            <div>
                <%= f.label :first_name %><br />
                <%= f.text_field :first_name, style:"width:100%", placeholder: "Spider" %>
            </div>
            <div>
                <%= f.label :last_name %><br />
                <%= f.text_field :last_name, style:"width:100%", placeholder: "Man" %>
            </div>
        </div>
        <div>
            <%= f.label :email %><br />
            <%= f.email_field :email, style:"width:100%", placeholder: "hello@booknroll.com" %>
        </div>

        <div>
            <%= f.label :password %><br />
            <%= f.password_field :password, style:"width:100%" %>
        </div>

        <div>
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, style:"width:100%" %>
        </div>

    <br>
    <div>

    <% if !user_signed_in? %>
    <%= f.submit "Create Account", class:"sign_up_button", style:"width:100%"%>
    <small>Already have an account? <small><%= link_to "Log in here.", new_session_path %></small></small>
    <% else %>
    <%= f.submit "Update Account", class:"sign_up_button", style:"width:100%"%>
    <% end %>
    </div>

        <%end%>
    </div>
</div>

app/views/users/edit.html.erb
<div class="description-text-area">
    <h1>User Profile</h1>
    <%= render 'form' %>
</div>

app/views/users/new.html.erb
<div class = "root-container">

  <section class="home-hero transparent root-item">
    <% if current_user.present? === false %>
      <div class="description-text-area">
        <div class="logo">
          <h1 class="user new">Sign up to book, teach, and enroll...</h1>
          <%= image_tag "https://i.ibb.co/7Q46BDP/logo.png", width: "100px"%>
        </div>
        <%= render 'users/form' %>
        
      </div>
    <% end %>
  </section>
</div>
<br><br><br>
<section class = "root-item">
<div class="popular-title">
  <h3>Popular Courses</h3>
</div>
    <%= render 'shared/courses_index', courses: Course.all.limit(8) %>

<div class="popular-title">
  <h3>Popular Rooms</h3>
</div>
    <%= render 'shared/rooms_index', rooms: Room.all.limit(8) %>
</section>

app/views/users/show.html.erb
<div class="container">

    <h1><%= @user.full_name %></h1>
    <button class="sign_up_button">
        <%= link_to "Edit Profile", edit_user_path(@user) %>
    </button>

    <div class="user-container">
        <% if current_user.rooms.length > 0 %>
            <div>
                <h2>Your Rooms</h2>
                <%= render 'shared/rooms_index',rooms: current_user.rooms %>
            </div>
        <% else %>
            <div class="link_container">
                <h3>Add a room ☞</h3>
                <div>
                <%= link_to new_room_path do %>
                    <%= image_tag "https://i.ibb.co/GtWqbN8/room1.jpg", class: "img-links" %>
                <% end %>
                </div>
        <% end %>
    </div>

    <% if current_user.courses.length > 0 %>
        <div>
            <h2>Your courses:</h2>
            <%= render 'shared/courses_index',courses: current_user.courses %>
        </div>
    <% else %>
        <div class="link_container">
            <h3> Add a course ☞ </h3>
            <div>
            <%= link_to new_course_path do %>
                <%= image_tag "https://i.ibb.co/qpR25vS/yoga.jpg", class: "img-links" %>
            <% end %>
            </div>
        </div>
    <% end %>

    <% if current_user.enrollments.length > 0 %>
        <div>
             <h2>Your enrollments:</h2>
             <%= render 'shared/courses_index',courses: Course.joins(:enrollments).where("enrollments.user_id = ?", current_user.id) %>
        </div>
    <% else %>
        <div class="link_container">
            <h3> Shop for a course ☞ </h3>
            <%= link_to courses_path do %>
                <%= image_tag "https://i.ibb.co/qpR25vS/yoga.jpg", class: "img-links" %>
            <% end %>
        </div>
    <% end %>

    </div>
</div>