config/routes.rb
Rails.application.routes.draw do

  root to: 'users#show'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  
  resources :courses do
    resources :enrollments do
      put :approving
      put :rejecting
    end
    resources :reviews, only: [:create, :destroy]
  end

  resources :rooms do
    resources :bookings do
      put :approving
      put :rejecting 
    end
  end
  
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    
    has_many :bookings, dependent: :destroy
    has_many :courses, through: :bookings

    has_many :searches, dependent: :destroy
    has_many :features, through: :searches
    has_many :availabilities, dependent: :destroy
    has_many :booker, through: :booking, source: :course

    validates :name, presence: true, uniqueness: { scope: :user_id }
    validates :address, presence: true
    validates :price, presence: true, numericality: { greater_than: 0 }
    validates :capacity, presence: true, numericality: { greater_than: 0 }

    private 

    def capitalize_name
        self.name.capitalize!
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_room, only: [:show, :edit, :update, :destroy]
    before_action :authorize!, only: [:edit, :update, :destroy]

    def new
        @room = Room.new
    end

    def create
        @room = Room.new room_params
        @room.user = current_user
        
        if params[:features]
            @room.features = params[:features].map do |feature|
                Feature.find_or_initialize_by(name: feature)
            end
        end

        if @room.save
            flash[:notice] = 'Congratulations! You have created a room.'
            redirect_to room_path(@room.id)
        else
            render :new
        end
    end

    def edit

    end

    def update

        if params[:features]
            @room.features = params[:features].map do |feature|
                Feature.find_or_initialize_by(name: feature)
            end
        end
        
        if @room.update room_params
            flash[:notice] = 'Room updated successfully'
            redirect_to room_path(@room.id)
        else
            render :edit
        end
    end

    def index
        if params[:feature]
            @feature = Feature.find_or_initialize_by(name: params[:feature])
            @rooms = @feature.rooms.order(created_at: :desc)
        elsif params[:location]
            @rooms = Room.all.filter { |room| room.location == params[:location] }
            @location = params[:location]
        else
            @rooms = Room.all.order(created_at: :desc)
        end
    end

    def show
        @availability = Availability.new
        @availabilities = @room.availabilities.order(created_at: :desc)
        @booking = Booking.new
        @bookings = @room.bookings.order(created_at: :desc)
        @courses = current_user.courses if current_user
    end

    def destroy
        @room.destroy
        flash[:notice] = 'The room was successfully deleted.'
        redirect_to rooms_path
    end

    private

    def find_room
        @room = Room.find params[:id]
    end
    
    def room_params
        params.require(:room).permit(:name, :location, :address, :capacity, :price, :description, :features)
    end

    def new_params
    end

    def authorize!
        unless can?(:crud, @room)
            redirect_to root_path, alert: 'Not Authorized'
        end
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: @room, local: true, class: "ui form") do |f|%>
    <div class="field">
        <% if @room.errors.present?%>
        <%= @room.errors.full_messages.join(', ')%>
        <% end %>
    </div>
    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, placeholder: "Spacious room with brand-new A/V system" %>
    </div>
    <div class="field">
        <%= f.label :address %><br>
        <%= f.text_area :address, rows: 2, placeholder: "123 Book n'Roll Road, New Westminster, BC" %>
    </div>
    <div class="field">
        <%= f.label :capacity %><br>
        <%= f.number_field :capacity %>
    </div>
    <div class="field">
        <%= f.label :price %><br>
        <%= f.number_field :price %>
    </div>
    <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description, rows:5 %>
    </div>

    <div class="locations field">
        <%= f.label :location %>
        <%= select(:room, :location, ["Arbutus Ridge", "Downtown", "Dunbar-Southlands", "Fairview",
        "Grandview-Woodland", "Kensington-Cedar Cottage", "Kerrisdale", "Killarney", "Kitsilano", 
        "Oakridge", "Marpole", "Mount Pleasant", "Renfrew-Collingwood", "Riley Park", "Shaughnessy", 
        "South Cambie", "Strathcona", "Sunset", "West End", "West Point Grey", "Burnaby", "Coquitlam", 
        "New Westminster", "Richmond"]) %>
    </div><br>

    <div class="features field">
        <h3 class="ui header">Features</h3>

        <%= check_box_tag("features[]", "Free Parking", find_feature(@room, "Free Parking")) %>
        <%= label_tag(:free_parking) %>

        <%= check_box_tag("features[]", "Paid Parking", find_feature(@room, "Paid Parking")) %>
        <%= label_tag(:paid_parking) %>

        <%= check_box_tag("features[]", "ADA Accessible", find_feature(@room, "ADA Accessible")) %>
        <%= label_tag(:ada_accessible, "ADA Accessible") %>

        <%= check_box_tag("features[]", "Audio/Visual Equipment", find_feature(@room, "Audio/Visual Equipment")) %>
        <%= label_tag(:audio_visual_equipment, "Audio/Visual Equipment") %>

        <%= check_box_tag("features[]", "WiFi", find_feature(@room, "WiFi")) %>
        <%= label_tag(:wifi, "WiFi") %>

        <%= check_box_tag("features[]", "Open Floor Plan", find_feature(@room, "Open Floor Plan")) %>
        <%= label_tag(:open_floor_plan) %>

        <%= check_box_tag("features[]", "Desks", find_feature(@room, "Desks")) %>
        <%= label_tag(:desks) %>

        <%= check_box_tag("features[]", "Whiteboard", find_feature(@room, "Whiteboard")) %>
        <%= label_tag(:whiteboard) %>
    </div>

    <br>
    <%= f.submit "Submit", class:"sign_up_button"%>

<% end %>

app/views/rooms/_list.html.erb
<% @rooms.each do |room| %>
<div class="single_room">
    <h5 class="new user"><%= link_to(room.name.truncate(30, separator: " "), room_path(room.id)) %></h5>
    <%= link_to(rooms_path(location: room.location)) do %>
            <i class="map marker alternate icon"></i><%= room.location %>
        <% end %>
    </h5>
    <hr />
    <p>Capacity: <%= room.capacity %></p>
    <p><%= room.description %></p>
    
</div>
<% end %>

app/views/rooms/edit.html.erb
<div class="container">
<h3>Edit Room</h3>

<%= render 'form' %>
</div>

app/views/rooms/index.html.erb
<div class="container">
    <h3 class="new user">Rooms Available</h3>
    <a href="<%= new_room_path%>" class="sign_up_button">New</a>
    
    <div class="filter">
        Filter rooms by:
        <div class="ui compact small menu">
            <div class="ui simple dropdown item">
                <p id="dropdown-title">Location</p>
            <i class="dropdown icon"></i>
                <div class="menu">
                    <div class="item"><%= link_to("Arbutus Ridge", rooms_path(location: "Arbutus Ridge")) %></div>
                    <div class="item"><%= link_to("Downtown", rooms_path(location: "Downtown")) %></div>
                    <div class="item"><%= link_to("Dunbar-Southlands", rooms_path(location: "Dunbar-Southlands")) %></div>
                    <div class="item"><%= link_to("Fairview", rooms_path(location: "Fairview")) %></div>
                    <div class="item"><%= link_to("Grandview-Woodland", rooms_path(location: "Grandview-Woodland")) %></div>
                    <div class="item"><%= link_to("Kensington-Cedar Cottage", rooms_path(location: "Kensington-Cedar Cottage")) %></div>
                    <div class="item"><%= link_to("Kerrisdale", rooms_path(location: "Kerrisdale")) %></div>
                    <div class="item"><%= link_to("Killarney", rooms_path(location: "Killarney")) %></div>
                    <div class="item"><%= link_to("Kitsilano", rooms_path(location: "Kitsilano")) %></div>
                    <div class="item"><%= link_to("Oakridge", rooms_path(location: "Oakridge")) %></div>
                    <div class="item"><%= link_to("Marpole", rooms_path(location: "Marpole")) %></div>
                    <div class="item"><%= link_to("Mount Pleasant", rooms_path(location: "Mount Pleasant")) %></div>
                    <div class="item"><%= link_to("Renfrew-Collingwood", rooms_path(location: "Renfrew-Collingwood")) %></div>
                    <div class="item"><%= link_to("Riley Park", rooms_path(location: "Riley Park")) %></div>
                    <div class="item"><%= link_to("Shaughnessy", rooms_path(location: "Shaughnessy")) %></div>
                    <div class="item"><%= link_to("Strathcona", rooms_path(location: "Strathcona")) %></div>
                    <div class="item"><%= link_to("Sunset", rooms_path(location: "Sunset")) %></div>
                    <div class="item"><%= link_to("West End", rooms_path(location: "West End")) %></div>
                    <div class="item"><%= link_to("West Point Grey", rooms_path(location: "West Point Grey")) %></div>
                    <div class="item"><%= link_to("Burnaby", rooms_path(location: "Burnaby")) %></div>
                    <div class="item"><%= link_to("Coquitlam", rooms_path(location: "Coquitlam")) %></div>
                    <div class="item"><%= link_to("New Westminster", rooms_path(location: "New Westminster")) %></div>
                    <div class="item"><%= link_to("Richmond", rooms_path(location: "Richmond")) %></div>
                    <div class="item"><%= link_to("Other", rooms_path(location: "Other")) %></div>
                </div>
            </div>
        </div>
                    

        <div class="ui compact small menu">
            <div class="ui simple dropdown item">
                <p id="dropdown-title">Feature</p>
                <i class="dropdown icon"></i>
                <div class="menu">
                    <div class="item"><%= link_to("Free Parking", rooms_path(feature: "Free Parking")) %></div>
                    <div class="item"><%= link_to("Paid Parking", rooms_path(feature: "Paid Parking")) %></div>
                    <div class="item"><%= link_to("ADA Accessible", rooms_path(feature: "ADA Accessible")) %></div>
                    <div class="item"><%= link_to("WiFi", rooms_path(feature: "WiFi")) %></div>
                    <div class="item"><%= link_to("Open Floor Plan", rooms_path(feature: "Open Floor Plan")) %></div>
                    <div class="item"><%= link_to("Audio/Visual Equipment", rooms_path(feature: "Audio/Visual Equipment")) %></div>
                    <div class="item"><%= link_to("Whiteboard", rooms_path(feature: "Whiteboard")) %></div>
                    <div class="item"><%= link_to("Desks", rooms_path(feature: "Desks")) %></div>
                </div>
            </div>
        </div>

    </div>

    <br><br>
    <hr />
    <br><br>

    <% if @feature.present? %>
        <h6>
            Showing rooms with:
            <span class="ui label">
                <%= @feature.name %>
            </span>
        </h6>

    <% elsif @location.present? %>
        <h6>
            Showing rooms in:
            <span class="ui label">
                <%= @location %>
            </span>
        </h6>
    <% end %>
    
    <%= render 'shared/rooms_index', rooms: @rooms %>
</div>

app/views/rooms/new.html.erb
<div class="container">
<h1 class="new user">Add Room</h1>

<%= render 'form' %>
</div>

app/views/rooms/show.html.erb
<div class="container">

  <div class="room_info">
    <div class="show_room_header">
        <div class="new user"><%= @room.name %>
            <%= link_to(rooms_path(location: @room.location)) do %>
              <div class="ui blue basic label">
                <i class="map marker alternate icon"></i><%= @room.location %>
              </div>
            <% end %>
        </div>
      </div>

    <% if can? :crud, @room %>
      <div class="post-buttons">
        <%= link_to('Edit', edit_room_path(@room.id), class: "sign_up_button") %>
        <%= link_to("Delete", room_path(@room), method: :delete, data:{confirm:'Are you sure?'}, class: "sign_up_button") %>
      </div>
    <% end %>
    <br>
    <div class="room_up">
      <div class="room_info">
        <p><strong>Address:</strong> <%= @room.address %></p>
        <p><strong>Capacity:</strong> <%= @room.capacity %></p>
        <p><strong>Price:</strong> $<%= @room.price %>/hr</p>
        <p><strong>Description:</strong> <br><%= @room.description %></p>

    <% if @room.features.count > 0 %>
      <p>
        <% @room.features.each do |feature| %>
        <%= link_to(
                    feature.name, rooms_path(feature: feature.name), class: "ui blue basic label"
                ) %>
        <% end %>
      </p>
    <% end %>
      
   </div>

  <% if current_user.present? && current_user.courses.present? %>
      <div class="booking_room">
        <%= form_with(model: [@room, @booking], local: true) do |form| %>
        <% if @booking.errors.present?%>
        <p style="color:red;">
          <%= @booking.errors.full_messages.join(', ') %>
        </p>
        <% end %>
        <div class=“field”>
          <%= form.label :start_time %><br />
          <%= form.datetime_select :start_time %>
        </div><br>
        <div class=“field”>
          <%= form.label :end_time %><br />
          <%= form.datetime_select :end_time %>
        </div><br>

        <div class=“field”>
          <%= form.label :course_id %><br />
          <%= form.collection_select :course_id, current_user.courses, :id, :title%>
        </div>
        <br>
        <div class=“actions”>
          <%= form.submit "Request Room", class: "sign_up_button" %>
        </div>
        <% end %>
      </div>
  <% end %>

  </div>
  <hr>


  <%= month_calendar events: @bookings do |date, bookings| %>
  <span class="day_number"><%= use_day_only date %></span class="day_number">
  <% bookings.each do |booking| %>
  <div>
    <div>
      <%= booking.start_time.strftime("%I:%M%p") %>
    </div>
    <% if booking.approved? %>
    <%= booking.course.title %>
    by <%= booking.course.user.first_name %>
    <% else %>
    <small> Pending </small>
    <%= link_to booking.course.title, edit_room_booking_path(@room, booking) %>
    <% end %>
    <div>
      <%= booking.end_time.strftime("%I:%M%p") %>
    </div>
  </div><br>
  <% end %>
  <% end %>

  <% if can?(:crud, @room)%>
  <h2> Pending Bookings </h2>
    <% @bookings.each do |booking| %>
      <% if booking.reserved? %>
        <%= link_to "Approve", room_booking_approving_path(@room, booking), method: :put, class: "sign_up_button" %>
        <%= link_to "Reject", room_booking_rejecting_path(@room, booking), method: :put, class: "sign_up_button" %>
        <%= booking.course.title  %>
      <% end %>
      <br><br>
    <% end %>
  <% end %>

  </div>

</div>