config/routes.rb
Rails.application.routes.draw do

  root to: 'users#show'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  
  resources :courses do
    resources :enrollments do
      put :approving
      put :rejecting
    end
    resources :reviews, only: [:create, :destroy]
  end

  resources :rooms do
    resources :bookings do
      put :approving
      put :rejecting 
    end
  end
  
end

app/views/layouts/_nav.html.erb
    <nav>
        <div class="the-menu  ui top fixed menu nav">
            <div class="item"><%=link_to "Book N'Roll", root_path, class:"navbar_link" %></div>
            <div class="login-menu item">
            <% if user_signed_in? %>
                Hello, <strong> <%= current_user.full_name %>&nbsp&nbsp&nbsp</strong>
                <%= link_to "Log Out", session_path, method: :delete,
                    data: {confirm: "Are you sure you want to log out?"}, 
                    class:"navbar_link"%>
            <% else %>
                <%= link_to "Log In", new_session_path, class:"navbar_link" %>
                <%= link_to "Sign Up", new_user_path, class:"navbar_link" %>
            <% end %>
            <% if user_signed_in?%>
                <%=link_to 'Home', root_path, class:"navbar_link" %>
            <% end %>
            <%=link_to 'Rooms', rooms_path, class:"navbar_link" %>

            <%=link_to 'Classes', courses_path, class:"navbar_link" %>

            <%# i want to ask everyone's opinion for the nav %>
            <div class="ui simple dropdown item">
                Menu
                <i class="dropdown icon"></i>
                <div class="menu">
                <div class="item">Home</div>
                <div class="item">Rooms</div>
                <div class="item">Courses</div>
            </div>
        </div>

        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    
<head>
  <title>Book n'Roll</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
  <%= favicon_link_tag asset_path('logo.png') %>
</head>

<body>
  <nav>
    <div class="the-menu  ui top fixed menu">
      <div class="item"><%=link_to "Book n'Roll", root_path, class:"navbar_link" %></div>
      <div class="login-menu item">
        <% if user_signed_in? %>
          Hello, <strong> <%= current_user.first_name %>&nbsp&nbsp&nbsp</strong>
        <%= link_to "Log Out", session_path, method: :delete,
              data: {confirm: "Are you sure you want to log out?"}, class:"navbar_link"%>
        <% else %>
          <%= link_to "Log In", new_session_path, class:"navbar_link" %>
          <%= link_to "Sign Up", new_user_path, class:"navbar_link" %>
        <% end %>
      <% if user_signed_in?%>
        <%=link_to 'Home', root_path, class:"navbar_link" %>
      <% end %>
        <%=link_to 'Rooms', rooms_path, class:"navbar_link" %>

        <%=link_to 'Courses', courses_path, class:"navbar_link" %>
      </div>
    </div>
  </nav>
  <%= yield %>
</body>

</html>